# Generated by Django 5.2.11 on 2026-02-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'managed': True},
        ),
    ]
