# Generated by Django 5.2.11 on 2026-02-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_dispatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dispatch_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'order_logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('card_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('main_group', models.CharField(blank=True, max_length=20, null=True)),
                ('chain', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sap_parties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('address_type', models.CharField(blank=True, max_length=1, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('address_name', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sap_party_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('sal_pack_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sap_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPartyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField()),
                ('card_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_party_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpl_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bpl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('card_code', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('bill_to_id', models.IntegerField(blank=True, null=True)),
                ('bill_to_address', models.TextField(blank=True, null=True)),
                ('ship_to_id', models.CharField(blank=True, null=True)),
                ('ship_to_address', models.TextField(blank=True, null=True)),
                ('dispatch_from_id', models.IntegerField(blank=True, null=True)),
                ('dispatch_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.IntegerField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('sap_doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.CharField()),
                ('status', models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pcs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ltrs', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
