# Generated by Django 6.0.1 on 2026-02-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='base_price',
            new_name='basic_price',
        ),
    ]
