# Generated by Django 5.2.11 on 2026-02-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyaddress',
            name='party',
        ),
    ]
