# Generated by Django 5.2.11 on 2026-02-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_remove_partyaddress_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyaddress',
            options={'managed': False, 'ordering': ['card_code', 'address_id'], 'verbose_name_plural': 'Party Addresses'},
        ),
    ]
