# Generated by Django 6.0.1 on 2026-01-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_state_code_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='users_company',
        ),
        migrations.AlterModelTable(
            name='maingroup',
            table='users_maingroup',
        ),
        migrations.AlterModelTable(
            name='state',
            table='users_state',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
        migrations.CreateModel(
            name='UserProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'item_code', 'category')},
            },
        ),
    ]
