# Generated by Django 6.0.1 on 2026-02-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_partyproductassignment_delete_userproductassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_group',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.maingroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.state'),
        ),
    ]
