# Generated by Django 5.2.11 on 2026-02-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_main_group_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_group',
            field=models.ForeignKey(blank=True, db_column='maingroup_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.maingroup'),
        ),
    ]
